"""auth sessions devices

Revision ID: 0002
Revises: 0001
"""
import sqlalchemy as sa
from alembic import op

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.String(length=80), nullable=False),
    sa.Column('platform', sa.String(length=12), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('app_version', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'installation_id'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_devices_user_id'), 'devices', ['user_id'], unique=False, schema='platform')
    op.create_table('login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(length=80), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('login_events_at', 'login_events', ['at'], unique=False, schema='platform')
    op.create_index('login_events_user_at', 'login_events', ['user_id', 'at'], unique=False, schema='platform')
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_password_resets_user_id'), 'password_resets', ['user_id'], unique=False, schema='platform')
    op.create_table('rate_limits',
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    schema='platform'
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('client', sa.String(length=12), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['platform.devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('sessions_user_active', 'sessions', ['user_id', 'revoked_at'], unique=False, schema='platform')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['platform.sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False, schema='platform')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_refresh_tokens_session_id'), table_name='refresh_tokens', schema='platform')
    op.drop_table('refresh_tokens', schema='platform')
    op.drop_index('sessions_user_active', table_name='sessions', schema='platform')
    op.drop_table('sessions', schema='platform')
    op.drop_table('rate_limits', schema='platform')
    op.drop_index(op.f('ix_platform_password_resets_user_id'), table_name='password_resets', schema='platform')
    op.drop_table('password_resets', schema='platform')
    op.drop_index('login_events_user_at', table_name='login_events', schema='platform')
    op.drop_index('login_events_at', table_name='login_events', schema='platform')
    op.drop_table('login_events', schema='platform')
    op.drop_index(op.f('ix_platform_devices_user_id'), table_name='devices', schema='platform')
    op.drop_table('devices', schema='platform')
    # ### end Alembic commands ###
