"""document store

Revision ID: 0003
Revises: 0002
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_rule', sa.String(length=80), nullable=False),
    sa.Column('write_rule', sa.String(length=80), nullable=False),
    sa.Column('max_docs_per_user', sa.Integer(), nullable=False),
    sa.Column('max_doc_bytes', sa.Integer(), nullable=False),
    sa.Column('audited', sa.Boolean(), nullable=False),
    sa.Column('realtime', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    schema='platform'
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection', sa.String(length=40), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection'], ['platform.collections.name'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('documents_collection_owner', 'documents', ['collection', 'owner_id', 'created_at'], unique=False, schema='platform')
    op.create_index('documents_data_gin', 'documents', ['data'], unique=False, schema='platform', postgresql_using='gin', postgresql_ops={'data': 'jsonb_path_ops'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('documents_data_gin', table_name='documents', schema='platform', postgresql_using='gin', postgresql_ops={'data': 'jsonb_path_ops'})
    op.drop_index('documents_collection_owner', table_name='documents', schema='platform')
    op.drop_table('documents', schema='platform')
    op.drop_table('collections', schema='platform')
    # ### end Alembic commands ###
