"""realtime events and chat

Revision ID: 0004
Revises: 0003
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('direct_key', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direct_key'),
    schema='platform'
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key'),
    schema='platform'
    )
    op.create_index('events_channel_id', 'events', ['channel', 'id'], unique=False, schema='platform')
    op.create_index(op.f('ix_platform_events_created_at'), 'events', ['created_at'], unique=False, schema='platform')
    op.create_table('chat_members',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_delivered_id', sa.BigInteger(), nullable=False),
    sa.Column('last_read_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['platform.chat_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id'),
    schema='platform'
    )
    op.create_index('chat_members_user', 'chat_members', ['user_id'], unique=False, schema='platform')
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['platform.chat_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'client_id'),
    schema='platform'
    )
    op.create_index('chat_messages_room_id', 'chat_messages', ['room_id', 'id'], unique=False, schema='platform')
    # ### end Alembic commands ###
    # Announce every committed event. NOTIFY is delivered only when the transaction commits, so a rolled-back change is never announced.
    op.execute("""
        create function platform.announce_event() returns trigger language plpgsql as $$
        begin perform pg_notify('platform_events', new.id::text); return null; end $$""")
    # Event ids must be committed in the order they are numbered, or a reader that has seen 6 would never be shown a 5 that commits later.
    # Taking a transaction-long lock and numbering the row after it makes that so, for every writer (this service and the web app alike).
    op.execute("""
        create function platform.order_event() returns trigger language plpgsql as $$
        begin perform pg_advisory_xact_lock(7403, 1); new.id := nextval('platform.events_id_seq'); return new; end $$""")
    op.execute("create trigger events_order before insert on platform.events for each row execute function platform.order_event()")
    op.execute("create trigger events_announce after insert on platform.events for each row execute function platform.announce_event()")


def downgrade():
    op.execute("drop trigger if exists events_order on platform.events")
    op.execute("drop function if exists platform.order_event()")
    op.execute("drop trigger if exists events_announce on platform.events")
    op.execute("drop function if exists platform.announce_event()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('chat_messages_room_id', table_name='chat_messages', schema='platform')
    op.drop_table('chat_messages', schema='platform')
    op.drop_index('chat_members_user', table_name='chat_members', schema='platform')
    op.drop_table('chat_members', schema='platform')
    op.drop_index(op.f('ix_platform_events_created_at'), table_name='events', schema='platform')
    op.drop_index('events_channel_id', table_name='events', schema='platform')
    op.drop_table('events', schema='platform')
    op.drop_table('chat_rooms', schema='platform')
    # ### end Alembic commands ###
