"""file storage

Revision ID: 0005
Revises: 0004
"""
import sqlalchemy as sa
from alembic import op

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('file_events_file', 'file_events', ['file_id', 'at'], unique=False, schema='platform')
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('folder', sa.String(length=120), nullable=False),
    sa.Column('storage_key', sa.String(length=80), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('ref_type', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key'),
    schema='platform'
    )
    op.create_index('files_owner', 'files', ['owner_id', 'deleted_at'], unique=False, schema='platform')
    op.create_index('files_ref', 'files', ['ref_type', 'ref_id'], unique=False, schema='platform')
    op.create_table('user_quotas',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    schema='platform'
    )
    op.create_table('file_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_key', sa.String(length=40), nullable=True),
    sa.Column('everyone', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['platform.files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'user_id', 'role_key', 'everyone'),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_file_shares_file_id'), 'file_shares', ['file_id'], unique=False, schema='platform')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_file_shares_file_id'), table_name='file_shares', schema='platform')
    op.drop_table('file_shares', schema='platform')
    op.drop_table('user_quotas', schema='platform')
    op.drop_index('files_ref', table_name='files', schema='platform')
    op.drop_index('files_owner', table_name='files', schema='platform')
    op.drop_table('files', schema='platform')
    op.drop_index('file_events_file', table_name='file_events', schema='platform')
    op.drop_table('file_events', schema='platform')
    # ### end Alembic commands ###
