"""jobs schedules alerts

Revision ID: 0007
Revises: 0006
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rule', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('alerts_open', 'alerts', ['rule'], unique=True, schema='platform', postgresql_where=sa.text('resolved_at is null'))
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('schedule', sa.String(length=60), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('jobs_dedupe', 'jobs', ['dedupe_key'], unique=True, schema='platform', postgresql_where=sa.text("status in ('queued', 'running')"))
    op.create_index('jobs_due', 'jobs', ['status', 'run_at'], unique=False, schema='platform')
    op.create_table('schedules',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('every_seconds', sa.Integer(), nullable=True),
    sa.Column('daily_at', sa.Time(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=10), nullable=True),
    sa.Column('last_job_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    schema='platform'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules', schema='platform')
    op.drop_index('jobs_due', table_name='jobs', schema='platform')
    op.drop_index('jobs_dedupe', table_name='jobs', schema='platform', postgresql_where=sa.text("status in ('queued', 'running')"))
    op.drop_table('jobs', schema='platform')
    op.drop_index('alerts_open', table_name='alerts', schema='platform', postgresql_where=sa.text('resolved_at is null'))
    op.drop_table('alerts', schema='platform')
    # ### end Alembic commands ###
